### ISSUE TITLE
Connection refused on port 3000 (DDEV + WP + ViteJS)

### ISSUE THREAD

**Issue by jmaleman** [ddev/ddev-browsersync#49] opened 2024-02-14 16:32 UTC
I'm working on a project with DDEV + WP + ViteJS on a Linux (Ubuntu). It's running correctly and I want to add ddev-browsersync to the project, but I not be able to reach `:3000` port with DDEV url.

**config.yaml**
```yaml
...
web_extra_exposed_ports:
    - name: ViteJS
      container_port: 5173
      http_port: 5172
      https_port: 5173
...
``` 
And an extra configuration file **docker-compose.vite_extra.yaml** for this:
```yaml
services:
  web:
    expose:
      - "5173"
    environment:
      HTTP_EXPOSE: ${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,5174:5173
      HTTPS_EXPOSE: ${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,5173:5173
```

When VIteJS configuration files are enable I can reach port `:3000` and browser indcates "ERR_CONNECTION_REFUSED".

¿Should be add an extra_exposed_ports on DDEV configuration file to achieve `:3000` like I did with ViteJS?

Thanks!

**Comment by rfay** [comment] 2024-02-14 16:36
If I understand right... you shouldn't be using 3000 at all here, ViteJS is running on 5173? You can easily `ddev ssh` and look at what's going on. You can `telnet localhost 5173` to see if it's live there. I imagine `telnet localhost 3000` will say connection refused.

**Comment by jmaleman** [comment] 2024-02-14 16:53
I'm login with SSH and seems to be able to connect at those ports.

![image](https://github.com/ddev/ddev-browsersync/assets/8301910/c115a48f-4356-434a-a7db-450bd18831f6)

**Comment by tyler36** [comment] 2024-02-15 00:34
The problem is caused by a conflict with the `environment`

```
environment:
      HTTP_EXPOSE: ${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,5174:5173
      HTTPS_EXPOSE: ${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,5173:5173
```

The browsersync addon also wants to set this value and when merged, only 1 `HTTPS_EXPOSE` value will be preserved.
You could remove the `#ddev-generated` from the conflicting files and take control.

**Comment by tyler36** [comment] 2024-02-15 00:37
I wonder, do you need browsersync? 
I use the browsersync addon to refresh the page when I make changes to asset files.
However, Vite also has this functionality. On my projects that use Vite, I find I don't need to use browsersync.

**Comment by tyler36** [comment] 2024-02-22 01:06
Closing. 

According to your Discord comments, you got BrowserSync working correctly and are working through a conflict with your config.
Feel free to PR any changes you think can improve the addon.

**Closed by tyler36** 2024-02-22 01:06 UTC
